algo = (input('Digite algo e eu falarei tudo possível sobre ele. escreva aqui: '))
print(f"o {algo} é um tipo {type(algo)}")
print(f'o {algo} é numérico? {algo.isnumeric()}')
print(f'o {algo} é um espaço? {algo.isspace()}')
print(f'o {algo} é decimal? {algo.isdecimal()}')
print(f'o {algo} é alfabético? {algo.isalpha()}')
print(f'o {algo} é alfanum? {algo.isalnum()}')
print(f'o {algo} é maiúsculos? {algo.isupper()}')
print(f'o {algo} é minúsculos? {algo.islower()}')
print(f'o {algo} é capitalizada? {algo.istitle()}')